# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rpai < Formula
  desc "Redpanda AI CLI — manage LLM providers, MCP servers, and connections"
  homepage "https://redpanda.com"
  version "0.2.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.redpanda.com/public/rpk-plugins/raw/names/rpai-darwin-amd64/versions/0.2.1/rpai_darwin_amd64.tar.gz"
      sha256 "521881ca3a29d87e620ada0ac62371c7de8fc1358444614357bdbf88567457c8"

      define_method(:install) do
        libexec.install "rpai"
        bin.install_symlink libexec/"rpai" => "rpai"
        generate_completions_from_executable(libexec/"rpai", "completion",
          shells: [:bash, :zsh, :fish], base_name: "rpai")
      end
    end
    if Hardware::CPU.arm?
      url "https://dl.redpanda.com/public/rpk-plugins/raw/names/rpai-darwin-arm64/versions/0.2.1/rpai_darwin_arm64.tar.gz"
      sha256 "ab0a835aa1493af64f68f6e6851c3becc446de4ad9d5fd1644e3990371659483"

      define_method(:install) do
        libexec.install "rpai"
        bin.install_symlink libexec/"rpai" => "rpai"
        generate_completions_from_executable(libexec/"rpai", "completion",
          shells: [:bash, :zsh, :fish], base_name: "rpai")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://dl.redpanda.com/public/rpk-plugins/raw/names/rpai-linux-amd64/versions/0.2.1/rpai_linux_amd64.tar.gz"
      sha256 "2a8b49a12e1ecfa29ef8e6ac0e5dbdf9e97fe1bff0b5433deaa2ff3c822cf792"
      define_method(:install) do
        libexec.install "rpai"
        bin.install_symlink libexec/"rpai" => "rpai"
        generate_completions_from_executable(libexec/"rpai", "completion",
          shells: [:bash, :zsh, :fish], base_name: "rpai")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://dl.redpanda.com/public/rpk-plugins/raw/names/rpai-linux-arm64/versions/0.2.1/rpai_linux_arm64.tar.gz"
      sha256 "72091067b07fe72faa83919deb63b60c14cb46c856d864ab0537af53165f43b4"
      define_method(:install) do
        libexec.install "rpai"
        bin.install_symlink libexec/"rpai" => "rpai"
        generate_completions_from_executable(libexec/"rpai", "completion",
          shells: [:bash, :zsh, :fish], base_name: "rpai")
      end
    end
  end

  test do
    assert_match(/rpai/, shell_output("#{bin}/rpai version"))
  end
end
