# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rpai < Formula
  desc "Redpanda AI CLI — manage LLM providers, MCP servers, and connections"
  homepage "https://redpanda.com"
  version "0.1.8"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.redpanda.com/public/rpk-plugins/raw/names/rpai-darwin-amd64/versions/0.1.8/rpai_darwin_amd64.tar.gz"
      sha256 "af54a0dbddad219b9a7dbd94f3ce8a22a41bd8b592c9de117c6928211734a629"

      define_method(:install) do
        libexec.install "rpai"
        bin.install_symlink libexec/"rpai" => "rpai"
        generate_completions_from_executable(libexec/"rpai", "completion",
          shells: [:bash, :zsh, :fish], base_name: "rpai")
      end
    end
    if Hardware::CPU.arm?
      url "https://dl.redpanda.com/public/rpk-plugins/raw/names/rpai-darwin-arm64/versions/0.1.8/rpai_darwin_arm64.tar.gz"
      sha256 "96cb97b64d260aea57d135ddf22e8bd3e10c8de479882cb17d6316b8f06a2fb4"

      define_method(:install) do
        libexec.install "rpai"
        bin.install_symlink libexec/"rpai" => "rpai"
        generate_completions_from_executable(libexec/"rpai", "completion",
          shells: [:bash, :zsh, :fish], base_name: "rpai")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://dl.redpanda.com/public/rpk-plugins/raw/names/rpai-linux-amd64/versions/0.1.8/rpai_linux_amd64.tar.gz"
      sha256 "a76d2b69cc2df172cd5aecbfa2611c795d71d8374f1341e1b79bbd2a4249c7c6"
      define_method(:install) do
        libexec.install "rpai"
        bin.install_symlink libexec/"rpai" => "rpai"
        generate_completions_from_executable(libexec/"rpai", "completion",
          shells: [:bash, :zsh, :fish], base_name: "rpai")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://dl.redpanda.com/public/rpk-plugins/raw/names/rpai-linux-arm64/versions/0.1.8/rpai_linux_arm64.tar.gz"
      sha256 "7bdb82a9a7c639bbb5cd9b3eccd7864146c54bfcb69d4d75bfcd4a22de4c69f2"
      define_method(:install) do
        libexec.install "rpai"
        bin.install_symlink libexec/"rpai" => "rpai"
        generate_completions_from_executable(libexec/"rpai", "completion",
          shells: [:bash, :zsh, :fish], base_name: "rpai")
      end
    end
  end

  test do
    assert_match(/rpai/, shell_output("#{bin}/rpai version"))
  end
end
